service: lastfm-weekly-chart
useDotenv: true
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  timeout: 10
  versionFunctions: false
  region: ap-northeast-1
functions:
  cronHandler:
    handler: index.handler
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0 0 ? * 2 *)
    environment:
      LF_API_KEY: ${env:LF_API_KEY}
      MISSKEY_TOKEN: ${env:MISSKEY_TOKEN}
custom:
  esbuild:
    bundle: true
    minify: false
    target: node18
    platform: node
plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin